// <auto-generated />
using APILibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APILibrary.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20230508122444_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APILibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@stud.kai.ru",
                            Name = "user1",
                            Password = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@stud.kai.ru",
                            Name = "user2",
                            Password = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@stud.kai.ru",
                            Name = "user3",
                            Password = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@stud.kai.ru",
                            Name = "user4",
                            Password = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@stud.kai.ru",
                            Name = "user5",
                            Password = "user5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "user6@stud.kai.ru",
                            Name = "user6",
                            Password = "user6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "user7@stud.kai.ru",
                            Name = "user7",
                            Password = "user7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "user8@stud.kai.ru",
                            Name = "user8",
                            Password = "user8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
